name: fair_ris_ai_env_CPU
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.16=h3f729d1_0
  - pip=25.1=pyhc872135_2
  - python=3.12.7=h14ffc60_0
  - setuptools=78.1.1=py312haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h5e9d12e_1
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - absl-py==2.3.1
      - attrs==25.3.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.1
      - ffmpeg==1.4
      - filelock==3.18.0
      - fonttools==4.58.5
      - fsspec==2025.5.1
      - grpcio==1.73.1
      - gymnasium==1.0.0
      - idna==3.10
      - jinja2==3.1.6
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - kaleido==0.1.0.post1
      - kiwisolver==1.4.8
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - narwhals==1.47.0
      - nbformat==5.10.4
      - networkx==3.2.1
      - numpy==2.1.1
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.3.0
      - platformdirs==4.3.8
      - plotly==6.0.0
      - protobuf==4.25.3
      - pygame==2.6.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywin32==311
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - rpds-py==0.26.0
      - scipy==1.14.1
      - six==1.17.0
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.0
      - torch==2.5.0
      - torch-tb-profiler==0.4.3
      - torchaudio==2.5.0
      - torchvision==0.20.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.11.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
