name: fair_ris_ai_env_GPU
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py312h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.7.15=haa95532_0
  - cffi=1.17.1=py312h827c3e9_1
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - expat=2.7.1=h8ddb27b_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py312h827c3e9_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py312haa95532_0
  - jpeg=9e=h827c3e9_3
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py312h827c3e9_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py312haa95532_0
  - numpy=2.0.1=py312hfd52020_1
  - numpy-base=2.0.1=py312h4dde369_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.17=h35632f6_0
  - pillow=11.1.0=py312h096bfcc_0
  - pip=25.1=pyhc872135_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.11=h716150d_0
  - pytorch=2.5.1=py3.12_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py312h827c3e9_0
  - setuptools=78.1.1=py312haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h5e9d12e_1
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - absl-py==2.2.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - ffmpeg==1.4
      - filelock==3.18.0
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - grpcio==1.71.0
      - gymnasium==1.0.0
      - idna==3.10
      - kiwisolver==1.4.8
      - markdown==3.7
      - matplotlib==3.9.2
      - narwhals==1.32.0
      - networkx==3.2.1
      - packaging==24.2
      - pandas==2.2.3
      - plotly==6.0.0
      - protobuf==4.25.3
      - pygame==2.6.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.3
      - scipy==1.14.1
      - six==1.17.0
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.0
      - torch-tb-profiler==0.4.3
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.11.0
      - tzdata==2025.2
      - urllib3==2.3.0
      - werkzeug==3.1.3
